dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://101.43.178.147:2181
  scan:
    base-packages: com.dubbo.provider.impl
server:
  port: 8001


