server:
  port: 8080
app:
  id: dong                                   #应用ID
apollo:
  cacheDir:  /Users/dong/                    #配置本地配置缓存目录
  cluster: default                           #指定使用哪个集群的配置
  meta: http://101.43.178.147:8080/          #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application,mysql            #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前



# 数据库地址
datasource:
  url: 101.43.178.147:3306/dong

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

  redis:
    database: 5
    # 配置redis的主机地址，需要修改成自己的
    host: 101.43.178.147
    port: 6379
    password: dongxuelei
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
  activemq:
    # activemq url
    broker-url: tcp://101.43.178.147:61616
    in-memory: true
    pool:
      # 如果此处设置为true，需要添加activemq-pool的依赖包，否则会自动配置失败，无法注入JmsMessagingTemplate
      enabled: false

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.dong.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml

logging:
  config: logback.xml
  level:
    com.itcodai.course03.dao: trace


dubbo:
  application:
    name: dubbo-consumer2
  registry:
    address: zookeeper://101.43.178.147:2181

