spring:
  # Redis配置
  redis:
    timeout: 6000 # 连接超时时长（毫秒）
    password: dongxuelei
    cluster:
      max-redirects: 3
      nodes:
        - 101.43.178.147:6379
        - 101.43.178.147:6389
        - 101.43.178.147:6399
        - 101.43.178.147:6479
        - 101.43.178.147:6489
        - 101.43.178.147:6499
    lettuce:
      pool:
        max-active: 1024 # 连接池最大连接数（默认为8，-1表示无限制 如果pool已经分配了超过max_active个jedis实例，则此时pool为耗尽）
        max-wait: 10000 #最大等待连接时间，单位毫秒 默认为-1，表示永不超时，超时会抛出JedisConnectionException
        max-idle: 10
        min-idle: 5
      shutdown-timeout: 100
server:
  port: 8005
